---
env:
  node: true
extends: "@chookslint/typescript"
parserOptions:
  project: "./tsconfig.json"
rules:
  "@typescript-eslint/naming-convention": "off"
  "@typescript-eslint/no-dynamic-delete": "off"
  "@typescript-eslint/no-empty-interface": "off"
  func-style: "off"
  multiline-ternary: "off"
  operator-linebreak: "off"
