---
overrides:
  - files: "*.test.ts"
    parserOptions:
      project: "tests/tsconfig.json"
    rules:
      "@typescript-eslint/no-empty-function": "off"
      "@typescript-eslint/no-non-null-assertion": "off"
