# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
env:
  node: true
ignorePatterns:
  - "dist/"
extends:
  - "@chookslint/typescript/strict"
  - "@chookslint/typescript/types"
parserOptions:
  project: tsconfig.lint.json
rules:
  "@typescript-eslint/consistent-type-imports": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/no-require-imports": off
