# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
env:
  node: true
ignorePatterns:
  - "dist/"
extends:
  - "@chookslint/typescript/strict"
  - "@chookslint/typescript/types"
parserOptions:
  project: tsconfig.lint.json
