---
env:
  node: true
root: true
extends:
  - '@chookslint/typescript'
parserOptions:
  project: ./tsconfig.json
overrides:
  - files: '*.js'
    rules:
      '@typescript-eslint/no-var-requires': 'off'
  - files: '*.test.ts'
    rules:
      '@typescript-eslint/no-empty-function': 'off'
      '@typescript-eslint/no-non-null-assertion': 'off'
rules:
  '@typescript-eslint/naming-convention': 'off'
  '@typescript-eslint/no-dynamic-delete': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  func-style: 'off'
  multiline-ternary: 'off'
  operator-linebreak: 'off'
