export { compile, unlink, write } from './compile.js'
export { resolveConfigFile, validateConfig, validateDevConfig } from './config.js'
export { diffCommand, diffOption } from './diff.js'
export { default as registerCommands } from './register.js'
export { default as resolveLocal } from './resolve.js'
export { getFileType, mapSourceFile, MODULES, sourceFromFile } from './sourcemap.js'
export type { FileOptions, FileType, SourceDir, SourceMap } from './sourcemap.js'
export { default as Store } from './store.js'
export { default as tokenToAppId } from './token-id.js'
export { transformModule, transformOption } from './transform.js'
