extends: lint/config.yml
overrides:
  - files: "*.js"
    rules:
      "@typescript-eslint/no-unsafe-argument": off
      "@typescript-eslint/explicit-module-boundary-types": off
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-call": off
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
